-- Seed data for the projects table
INSERT INTO projects (name, "desc", url, stack, photo_url, type, order_index, repo_url)
VALUES
    ('Payable Africa', 'The ultimate payment solution for your businesses. Optimize your payment process, pay your vendors with ease and get paid on time.', 'https://payable.africa', '["React", "Node", "Microservices", "AWS", "Redis", "REST", "Sequelize", "RabbitMQ", "MySQL", "NestJs", "Typescript"]', '["/project/payable-africa.png", "/project/payable-africa-II.png", "/project/payable-africa-III.png"]', 'Web Application', 0, NULL),
    ('Varroe', 'The future of small business booking and appointment services. The company has created a product that allows customers to have greater control over their service choices, and gives businesses all the information they need to provide the services to the best of their ability.', 'https://varroe.com', '["React", "Node", "Sequelize", "MySQL", "KnexJs", "Typescript"]', '["/project/varroe.png", "/project/varroe-II.png"]', NULL, 1, NULL),
    ('Calen360', 'Calen360 allows you to sync your calendars with minimal effort, no more worrying about manually transferring your calendars!', 'https://app.calen360.com', '["React", "AntDesign", "NextJs", "TailwindCSS", "Typescript"]', '["/project/calen360.png", "/project/calen360-I.png"]', NULL, 2, NULL),
    ('Buypower', 'Pay Electricity Bills Online in Nigeria on BuyPower. Buy Prepaid and Postpaid Meter units for AEDC, JED, EKEDC, IBEDC, IKEDC, EEDC, KAEDCO, KEDCO and PHED.', 'https://buypower.ng', '["React", "Node", "Sequelize", "MySQL", "KnexJs", "Javascript"]', '["/project/buypower.png"]', NULL, 3, NULL),
    ('Luxiiva', '', 'https://luxiiva.com', '["Shopify", "Javascript", "CMS"]', '["/project/luxiiva.png", "/project/luxiiva-II.png"]', NULL, 4, NULL),
    ('Dwtenergia', 'DWT Energia Limited is an integrated Oil and Gas services company that specializes in providing comprehensive solutions to the energy industry. With a rich history and a strong presence in the market, DWT Energia is committed to delivering excellence in every aspect of its operations. ', 'https://dwtenergia.nulll.xyz/#core-services', '["React", "Javascript"]', '["/project/dwtenergia.png"]', NULL, 5, NULL),
    ('Yugeeproperties', 'TenantOccupying or renting a property? This is for you.', 'https://yugeeproperties.com', '["React", "Javascript"]', '["/project/yugeeproperties.png"]', NULL, 6, NULL),
    ('Platabox', 'Dispatch hailing made easy Platabox is a dispatch hailing platform that provides fast and affordable connection between customers and registered dispatchers. with just a few tap of buttons, you can request for a dispatch rider and get your package delivered to your desired destination(s)', 'https://apkpure.com/platabox/com.platabox.plataboxandroid', '["React Native", "Node", "Sequelize", "MySQL", "KnexJs", "Javascript"]', '["/project/platabox.png"]', NULL, 7, NULL);

-- Seed data for the experience table
INSERT INTO experience (start_date, end_date, position, company, "desc", skills, order_index)
VALUES
    ('2024', 'Present', 'Senior Fullstack Developer', 'Varroe', '[]', '["TypeScript", "React.js", "Cascading Style Sheets (CSS)", "Web Development", "JavaScript", "Agile & Waterfall Methodologies", "ESLint", "Redux.js", "Next.js", "Front-End Development Node.js", "Web Development", "Express.js", "Agile & Waterfall Methodologies", "ESLint", "Databases", "System Architecture", "Representational State Transfer (REST)", "Sequelize.js", "SQL", "Object-Oriented Programming (OOP)", "PostgreSQL", "Tailwind CSS"]', 0),
    ('2024', '2024', 'Senior Backend Developer', 'Fincra Technologies', '[]', '["Knex", "Systems Design & Architecture", "Payment Services", "NodeJs", "RabbitMQ", "AWS", "Typescript", "Javascript", "Redis", "MySQL", "Microservices", "SCRUM & Agile Methodology", "MongoDB", "GraphQL"]', 1),
    ('2021', '2024', 'Full Stack Developer', 'BuyPower (YC W17)', '[]', '["TypeScript", "Node.js", "React.js", "Core Banking", "mui", "Web Development", "Express.js", "JavaScript", "Back-End Web Development", "Agile & Waterfall Methodologies", "Tailwind CSS", "Bash", "ESLint", "Payment Services", "Redux.js", "Microservices", "Data Caching", "Amazon Web Services (AWS)", "Redis", "Representational State Transfer (REST)", "Sequelize.js", "RabbitMQ", "MySQL"]', 2),
    ('2023', '2024', 'Frontend Developer', 'Perizer', '[]', '["TypeScript", "Node.js", "Web Development", "Agile & Waterfall Methodologies", "Tailwind CSS", "ESLint", "Agile Methodologies", "Next.js", "Front-End Development", "Ant Design"]', 3),
    ('2023', '2023', 'Frontend Web Developer - Contract', 'SimpleMarket Inc. (BetaStore.co)', '[]', '["TypeScript", "React.js", "chakra-ui", "Web Development", "JavaScript", "Agile & Waterfall Methodologies", "ESLint", "Redux.js", "pnpm", "Front-End Development", "vite", "Web Development", "Tailwind CSS", "React Hooks", "React Context", "React Testing Library", "Jest", "RTK Query"]', 4),
    ('2022', '2022', 'Full Stack Developer - Contract', 'Varroe', '["Developed and maintained customer-facing web application interfaces using ReactJS, Next.js, and Tailwind CSS.", "Translated designs into responsive and visually appealing UIs", "Optimized performance (Next.js SSR) for faster load times", "Integrated Node.js APIs for dynamic content.", "Ensured cross-browser compatibility.", "Developed core API for business finder solution.", "Led initial backend development, establishing a scalable system."]', '["TypeScript", "React.js", "Cascading Style Sheets (CSS)", "Web Development", "JavaScript", "Agile & Waterfall Methodologies", "ESLint", "Redux.js", "Next.js", "Front-End Development Node.js", "Web Development", "Express.js", "Agile & Waterfall Methodologies", "ESLint", "Databases", "System Architecture", "Representational State Transfer (REST)", "Sequelize.js", "SQL", "Object-Oriented Programming (OOP)", "PostgreSQL", "Tailwind CSS"]', 5),
    ('2021', '2021', 'Full-stack Developer - Freelance', 'Vastovers Stemordz Ltd', '["Developed a complete online store for Vastover Stemordz Ltd, a pharmaceutical company in Abuja, Nigeria.", "Upgraded their outdated system to a modern e-commerce platform.", "Built the entire app from scratch, including the front-end and back-end.", "Made sure the old and new systems could work together smoothly.", "Created user-friendly features and designs to make shopping easier.", "Worked closely with the company to understand their needs and meet their requirements.", "Ensured the website was secure and protected customer information.", "Tested everything thoroughly to fix any problems and make it run smoothly.", "Provided ongoing support and maintenance to keep the website running well.", "Helped Vastover Stemordz Ltd grow their online sales and reach more customers in the pharmaceutical industry."]', '["React.js", "Web Development", "Back-End Web Development", "Python (Programming Language)", "Representational State Transfer (REST)", "Front-End Development", "E-commerce", "Web Design", "Web Application Development", "PostgreSQL", "Redux.js", "Flask", "Databases"]', 6),
    ('2021', '2021', 'NYSC Attaché - Support Personnel', 'Inlaks Nigeria', '["At INLAKS Ltd., the sole distributor of Temenos T24 in Sub-Saharan Africa, I provided support for the core banking sector on a project with CBN. I gained hands-on experience with T24, running batch scripts, subroutines, and database queries to improve performance and reduce redundancy. Working extensively with the terminal, I deepened my understanding of core banking concepts and system limitations, enhancing my problem-solving skills and ability to work under pressure. This experience equipped me with the technical expertise to contribute effectively to banking and financial technology solutions."]', '["cmd", "Bash", "jBase", "SQL", "MySQL", "window server", "Linux", "Temenos T24", "Core Banking", "Banking", "Financial Technology", "Batch Processing", "Database Management", "System Administration"]', 7),
    ('2019', '2019', 'Software Developer Intern', 'Pyrich Group Limited', '["I developed and enhanced a full-stack web application for a government agency to manage visitor information and streamline operations. My role involved building core functionalities, improving existing systems, and troubleshooting bugs to enhance system reliability. This experience strengthened my problem-solving skills, attention to detail, and understanding of quality assurance in real-world software development."]', '["Node.js", "React.js", "Web Design", "Web Development", "Express.js", "Back-End Web Development", "Databases", "Redux.js", "Knex.js", "Representational State Transfer (REST)", "PostgreSQL", "Front-End Development", "SaaS Development"]', 8);
